- id: at_home
  alias: En casa
  trigger:
  - entity_id: group.familia
    from: not_home
    platform: state
    to: home
  action:
  - data:
      entity_id: climate.caldera_dia
      temperature: 20
    service: climate.set_temperature
  - data:
      entity_id: climate.caldera_noche
      temperature: 18
    service: climate.set_temperature
- id: not_home
  alias: Todos fuera
  trigger:
  - entity_id: group.familia
    from: home
    platform: state
    to: not_home
  action:
  - data:
      entity_id: climate.caldera_dia
      temperature: 10
    service: climate.set_temperature
  - data:
      entity_id: climate.caldera_noche
      temperature: 10
    service: climate.set_temperature

- id: caldera_noche
  alias: Caldera por la noche
  trigger:
  - at: '20:00'
    platform: time
  action:
  - data:
      entity_id: climate.caldera_noche
      temperature: 18
    service: climate.set_temperature
  - data:
      entity_id: climate.caldera_dia
      temperature: 10
    service: climate.set_temperature
  condition:
  - condition: state
    entity_id: group.familia
    state: home

- id: caldera_dia
  alias: Caldera por el dia
  trigger:
  - at: '7:00'
    platform: time
  action:
  - data:
      entity_id: climate.caldera_dia
      temperature: 20
    service: climate.set_temperature
  - data:
      entity_id: climate.caldera_noche
      temperature: 10
    service: climate.set_temperature
  condition:
  - condition: state
    entity_id: group.familia
    state: home
